#!/bin/sh
#
# @name E-Flite Opterra
#
# @type Flying Wing
# @class Plane
#
# @board bitcraze_crazyflie exclude
#

. ${R}etc/init.d/rc.fw_defaults

param set-default MAV_TYPE 1 # fixed wing aircraft
param set-default CA_AIRFRAME 1

# Control Allocation settings
param set-default CA_ROTOR_COUNT 1
param set-default CA_ROTOR0_PX 0.15
param set-default CA_SV_CS_COUNT 2
param set-default CA_SV_CS0_TYPE 5
param set-default CA_SV_CS0_TRQ_P 0.5
param set-default CA_SV_CS0_TRQ_R -0.5
param set-default CA_SV_CS1_TYPE 6
param set-default CA_SV_CS1_TRQ_P 0.5
param set-default CA_SV_CS1_TRQ_R 0.5

# Actuator settings
param set-default PWM_AUX_FUNC1 201
param set-default PWM_AUX_FUNC2 202
param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_DIS1 980
param set-default PWM_MAIN_MIN1 1200
param set-default PWM_MAIN_MAX1 1400

# Airspeed settings
param set-default SENS_EN_MS4525DO 1 # enable the MS4525DO airspeed sensor
param set-default FW_AIRSPD_STALL 9.0
param set-default FW_AIRSPD_MIN 12.0
param set-default FW_AIRSPD_MAX 30.0
param set-default FW_AIRSPD_TRIM 15.0
param set-default CAL_AIR_TUBELEN 25

# GNSS settings for HERE 3+
param set-default UAVCAN_ENABLE 2

# Gimbal settings Siyi A8
param set-default MNT_MODE_IN 0 # auto
param set-default MNT_MODE_OUT 2 # Gimbal v2.0
param set-default MNT_DO_STAB 0 # A8 has a built-in stabilization
param set-default MAV_1_CONFIG 102
param set-default MAV_1_FORWARD 1
param set-default MAV_1_MODE 0
param set-default SER_TEL2_BAUD 115200
