#!/bin/sh
#
# @name E-Flite Opterra
#
# @type Flying Wing
# @class Plane
#
# @board bitcraze_crazyflie exclude
#

. ${R}etc/init.d/rc.fw_defaults

param set-default MAV_TYPE 1 # fixed wing aircraft
param set-default CA_AIRFRAME 1

param set-default CA_ROTOR_COUNT 1
param set-default CA_ROTOR0_PX 0.15
param set-default CA_SV_CS_COUNT 2
param set-default CA_SV_CS0_TYPE 5
param set-default CA_SV_CS0_TRQ_P 0.5
param set-default CA_SV_CS0_TRQ_R -0.5
param set-default CA_SV_CS1_TYPE 6
param set-default CA_SV_CS1_TRQ_P 0.5
param set-default CA_SV_CS1_TRQ_R 0.5

param set-default SENS_EN_MS4525DO 1 # enable the MS4525DO airspeed sensor

# Actuator settings
param set-default PWM_AUX_FUNC1 201
param set-default PWM_AUX_FUNC2 202
param set-default PWM_MAIN_FUNC1 101
